# Generated by Django 4.2.2 on 2024-11-27 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_rezerv', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 10, 42, 45, 611229), verbose_name='Время окончания брони'),
            preserve_default=False,
        ),
    ]
