# Generated by Django 4.2.2 on 2024-11-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('main_banner', 'Баннер (Главная)'), ('main_contacts_image', 'Картинка для контактов (Главная)'), ('about_team_image', 'Команда (О ресторане)'), ('about_history_image', 'История ресторана (О ресторане)'), ('reservation_banner', 'Баннер страницы бронирования')], max_length=50, unique=True, verbose_name='Ключ изображения')),
                ('image', models.ImageField(upload_to='site_images/', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Изображение сайта',
                'verbose_name_plural': 'Изображения сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('main_description', 'Описание ресторана (Главная)'), ('main_services', 'Услуги ресторана (Главная)'), ('main_contacts', 'Контактная информация (Главная)'), ('main_feedback', 'Обратная связь (Главная)'), ('about_history', 'История ресторана (О ресторане)'), ('about_mission', 'Миссия и ценности (О ресторане)'), ('about_team', 'Команда (О ресторане)'), ('reservation_form', 'Форма бронирования (Бронирование)'), ('reservation_availability', 'Доступность столиков (Бронирование)'), ('reservation_confirmation', 'Подтверждение бронирования (Бронирование)')], max_length=50, unique=True, verbose_name='Ключ текста')),
                ('value', models.TextField(verbose_name='Текст')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Текст сайта',
                'verbose_name_plural': 'Тексты сайта',
            },
        ),
    ]
