# Generated by Django 4.2.2 on 2024-11-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_images/services', verbose_name='Картинка')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('main_banner', 'Баннер (Главная)'), ('main_contacts_image', 'Картинка для контактов (Главная)'), ('about_history_image', 'История ресторана (О ресторане)'), ('reservation_banner', 'Баннер страницы бронирования')], max_length=50, unique=True, verbose_name='Ключ изображения')),
                ('image', models.ImageField(upload_to='site_images/', verbose_name='Изображение основное')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Изображение 3')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Изображение сайта',
                'verbose_name_plural': 'Изображения сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('main_description', 'Описание ресторана (Главная)'), ('main_contacts', 'Контактная информация (Главная)'), ('about_history', 'История ресторана (О ресторане)'), ('about_mission', 'Миссия и ценности (О ресторане)')], max_length=50, unique=True, verbose_name='Ключ текста')),
                ('value', models.TextField(verbose_name='Текст основной')),
                ('value_1', models.TextField(blank=True, null=True, verbose_name='Текст 1')),
                ('value_2', models.TextField(blank=True, null=True, verbose_name='Текст 2')),
                ('value_3', models.TextField(blank=True, null=True, verbose_name='Текст 3')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Текст сайта',
                'verbose_name_plural': 'Тексты сайта',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Фамилия')),
                ('image', models.ImageField(upload_to='site_images/staff', verbose_name='Картинка')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
