# Generated by Django 4.2.2 on 2024-11-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='key',
            field=models.CharField(choices=[('main_banner', 'Баннер (Главная)'), ('about_history_image', 'История ресторана (О ресторане)'), ('reservation_banner', 'Баннер страницы бронирования')], max_length=50, unique=True, verbose_name='Ключ изображения'),
        ),
    ]
