# Generated by Django 4.2.2 on 2024-11-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_siteimage_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetext',
            name='key',
            field=models.CharField(choices=[('main_description', 'Описание ресторана (Главная)'), ('main_contacts', 'Контактная информация (Главная)'), ('about_history', 'История ресторана (О ресторане)'), ('about_mission', 'Миссия и ценности (О ресторане)'), ('site_title', 'Название сайта')], max_length=50, unique=True, verbose_name='Ключ текста'),
        ),
    ]
